In [43]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,


df = pd.read_excel('a_Dataset_CreditScoring.xlsx')

In [44]:
df

,TARGET,ID,DerogCnt,CollectCnt,BanruptcyInd,InqCnt06,InqTimeLast,InqFinanceCnt24,TLTimeFirst,TLTimeLast,...,TL50UtilCnt,TLBalHCPct,TLSatPct,TLDel3060Cnt24,TLDel90Cnt24,TLDel60CntAll,TLOpenPct,TLBadDerogCnt,TLDel60Cnt24,TLOpen24Pct
0,1.0,582,3.0,3.0,0.0,4.0,0.0,5.0,117.0,27.0,...,3.0,0.9179,0.2083,2.0,3.0,7.0,0.2083,4.0,4.0,0.0000
1,1.0,662,15.0,9.0,0.0,3.0,1.0,3.0,14.0,14.0,...,1.0,0.8000,0.0000,0.0,0.0,0.0,1.0000,12.0,0.0,1.0000
2,1.0,805,0.0,0.0,0.0,1.0,5.0,1.0,354.0,7.0,...,5.0,0.3552,0.6538,0.0,1.0,1.0,0.7308,1.0,1.0,0.5263
3,1.0,1175,8.0,5.0,0.0,6.0,1.0,10.0,16.0,4.0,...,3.0,0.9127,0.2500,1.0,1.0,1.0,0.7500,7.0,1.0,1.3333
4,1.0,1373,3.0,1.0,0.0,9.0,0.0,8.0,130.0,52.0,...,1.0,1.2511,0.0000,0.0,1.0,4.0,0.1429,3.0,1.0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.0,126441,0.0,0.0,0.0,2.0,0.0,2.0,199.0,10.0,...,9.0,0.7853,0.6923,0.0,0.0,0.0,0.6538,0.0,0.0,0.3529
2996,0.0,126448,0.0,0.0,0.0,0.0,NaN,0.0,270.0,3.0,...,5.0,0.5766,0.9286,0.0,0.0,0.0,0.8571,0.0,0.0,0.4167
2997,0.0,126465,1.0,1.0,0.0,8.0,0.0,5.0,234.0,4.0,...,9.0,0.8722,0.6071,0.0,0.0,0.0,0.4286,1.0,0.0,0.7500
2998,0.0,126487,4.0,4.0,0.0,2.0,3.0,1.0,257.0,3.0,...,3.0,1.0391,0.6000,0.0,1.0,2.0,0.6000,4.0,1.0,1.0000
2999,0.0,126503,2.0,1.0,1.0,0.0,18.0,0.0,254.0,119.0,...,1.0,0.3239,0.1667,0.0,2.0,4.0,0.5000,3.0,2.0,0.0000

In [45]:
df.drop(['ID'],axis=1,inplace=True)

In [46]:
df.isna().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [47]:
df.shape

(3000, 29)

In [48]:
df = df.fillna(df.mean())

In [49]:
df.isna().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [50]:
x = df.iloc[:,1:28].values
y = df.iloc[:,0].values

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=00)

In [51]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [52]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [53]:
print(accuracy_score(y_test,y_pred))

0.8283333333333334

In [56]:
predictions = lr.predict_proba(x_test)

pred_prob = pd.DataFrame(predictions,columns=['prob0','prob1'])
pred_target = pd.DataFrame(lr.predict(x_test),columns=['Predicted Target'])
test_dataset = pd.DataFrame(y_test,columns=['Actual Outcome'])

In [57]:
final_df = pd.concat([test_dataset,pred_prob,pred_target],axis=1)
final_df.to_csv('Prediction.csv',sep=',',encoding='UTF-8')

In [58]:
final_df.head()

   Actual Outcome     prob0     prob1  Predicted Target
0             1.0  0.042301  0.957699               1.0
1             0.0  0.936833  0.063167               0.0
2             0.0  0.704597  0.295403               0.0
3             0.0  0.908269  0.091731               0.0
4             0.0  0.866217  0.133783               0.0